#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Render the TSV captures in ``tests/fixtures/real`` into an on-disk replica of
the six listings, using each site's own index dialect.

    python3 tools/build_snapshot.py --out /tmp/snapshots

The result is a directory tree that can be served by ``tests/replica_server.py``
and crawled with ``--rewrite`` so that the crawler sees the real URLs while the
bytes come from the local disk. ``tools/snapshot_inventory.py`` wires that up.

Captures are faithful in *content* (names, dates, sizes exactly as published);
the markup is regenerated, so this is a behavioural snapshot, not a byte copy.
"""

from __future__ import annotations

import argparse
import html
import os
import sys
import urllib.parse
from typing import Dict, List

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FIXTURES = os.path.join(ROOT, "tests", "fixtures", "real")

# capture file -> (site, listing path, dialect)
CAPTURES: List[Dict[str, str]] = [
    {"file": "pgfn_root.tsv", "site": "dadosabertos.pgfn.gov.br", "path": "/",
     "dialect": "links", "title": "Index of /"},
    {"file": "pgfn_2025_trimestre_04.tsv", "site": "dadosabertos.pgfn.gov.br",
     "path": "/2025_trimestre_04/", "dialect": "links",
     "title": "Index of /2025_trimestre_04/"},
    {"file": "macau_root.tsv", "site": "macau.rn.gov.br", "path": "/diario/",
     "dialect": "links", "title": "Index of /diario/"},
    {"file": "macau_2013.tsv", "site": "macau.rn.gov.br",
     "path": "/diario/2013 - Diário Oficial de Macau/", "dialect": "links",
     "title": "Index of /diario/2013 - Diário Oficial de Macau"},
    {"file": "comissao_upload.tsv", "site": "comissaodaverdade.al.sp.gov.br",
     "path": "/upload/", "dialect": "links", "title": "Index of /upload"},
    {"file": "cvm_root.tsv", "site": "dados.cvm.gov.br", "path": "/dados/",
     "dialect": "pre", "title": "Index of /dados/"},
    {"file": "cvm_cad.tsv", "site": "dados.cvm.gov.br", "path": "/dados/ADM_CART/",
     "dialect": "pre", "title": "Index of /dados/ADM_CART/"},
    {"file": "cvm_cia_aberta_dados.tsv", "site": "dados.cvm.gov.br",
     "path": "/dados/CIA_ABERTA/CAD/DADOS/", "dialect": "pre",
     "title": "Index of /dados/CIA_ABERTA/CAD/DADOS/"},
    {"file": "macau_2013_03.tsv", "site": "macau.rn.gov.br",
     "path": "/diario/2013 - Diário Oficial de Macau/03 - Março-2013/", "dialect": "links",
     "title": "Index of /diario/2013 - Diário Oficial de Macau/03 - Março-2013"},
    {"file": "valiprev_pdf.tsv", "site": "valiprev.sp.gov.br",
     "path": "/uploads/paginas/certidoes/pdf/", "dialect": "table",
     "title": "Index of /uploads/paginas/certidoes/pdf"},
]

BANNER = ("<!-- offline snapshot of {url}\n"
          "     captured {date} via the platform fetcher; markup regenerated by\n"
          "     tools/build_snapshot.py from tests/fixtures/real/{capture}\n"
          "     names/dates/sizes are verbatim; this is not the server's own HTML -->\n")


def parse_tsv(path: str) -> List[Dict[str, str]]:
    rows: List[Dict[str, str]] = []
    with open(path, encoding="utf-8") as fh:
        header = fh.readline().rstrip("\n").split("\t")
        for line in fh:
            line = line.rstrip("\n")
            if not line.strip():
                continue
            cells = line.split("\t")
            cells += [""] * (len(header) - len(cells))
            rows.append(dict(zip(header, cells)))
    return rows


def absolute_url(row: Dict[str, str], site: str, path: str) -> str:
    if row.get("url"):
        return row["url"]
    return "https://{}{}{}".format(site, path, urllib.parse.quote(row["name"], safe=""))


def render_links(rows, site, path, title) -> str:
    """Metadata-less link list (PGFN, Macau, OpenDataSoft)."""
    items = []
    for row in rows:
        url = absolute_url(row, site, path)
        items.append('    <p><a href="{}">{}</a></p>'.format(
            html.escape(url, quote=True), html.escape(row["name"])))
    return ("""<!DOCTYPE html>
<html lang="pt-BR"><head><meta charset="utf-8"><title>{title}</title></head>
<body><h1>{title}</h1>
{items}
</body></html>
""").format(title=html.escape(title), items="\n".join(items))


def render_pre(rows, site, path, title) -> str:
    """Apache <pre> index, as used by dados.cvm.gov.br."""
    parent = path.rstrip("/").rsplit("/", 1)[0] + "/" if path.strip("/") else "/"
    lines = ['<img src="/icons/back.gif" alt="[PARENTDIR]"> '
             '<a href="{}">Parent Directory</a>                             -   '.format(parent)]
    for row in rows:
        name = row["name"]
        href = urllib.parse.quote(name, safe="") + ("/" if row["kind"] == "dir" else "")
        icon = "folder.gif" if row["kind"] == "dir" else "compressed.gif"
        shown = "-" if row["kind"] == "dir" else (row["size"] or "-")
        lines.append('<img src="/icons/{}" alt="[   ]"> <a href="{}">{}</a>  {}   {}'.format(
            icon, href, html.escape(name), row["date"] or "-", shown))
    return """<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>{title}</title>
 </head>
 <body>
<h1>{title}</h1>
<pre><img src="/icons/blank.gif" alt="Icon "> <a href="?C=N;O=D">Name</a>                    <a href="?C=M;O=A">Last modified</a>      <a href="?C=S;O=A">Size</a>  <a href="?C=D;O=A">Description</a><hr>
{rows}
<hr></pre>
</body></html>
""".format(title=html.escape(title), rows="\n".join(lines))


def render_table(rows, site, path, title) -> str:
    """Apache 2.4 table index with truncated cells + link titles (valiprev)."""
    body = []
    for row in rows:
        name = row["name"]
        href = urllib.parse.quote(name, safe="") + ("/" if row["kind"] == "dir" else "")
        display = html.escape(name[:20] + "..&gt;") if len(name) > 22 else html.escape(name)
        body.append(
            '  <tr><td class="{}"><img src="/icons/{}.gif" alt="[ ]"></td>'
            '<td><a href="{}" title="{}">{}</a></td>'
            '<td class="datetime">{}</td><td class="size">{}</td>'
            '<td class="description">&nbsp;</td></tr>'.format(
                row["kind"], row["kind"], href, html.escape(name), display,
                row["date"] or "-", row["size"] or "-"))
    return """<!DOCTYPE html>
<html><head><title>{title}</title>
<meta charset="utf-8"></head><body>
<h1>{title}</h1>
<table id="indexlist">
 <tr><th class="indexcolicon"><img src="/icons/blank.gif" alt="[ICO]"></th>
     <th><a href="?C=N;O=D">Name</a></th>
     <th><a href="?C=M;O=A">Last modified</a></th>
     <th><a href="?C=S;O=A">Size</a></th>
     <th><a href="?C=D;O=A">Description</a></th></tr>
 <tr><th colspan="5"><hr></th></tr>
 <tr><td class="indexcolicon"><img src="/icons/back.gif" alt="[PARENTDIR]"></td>
     <td><a href="../">Parent Directory</a></td><td>&nbsp;</td>
     <td class="indexcolsize">-</td><td>&nbsp;</td></tr>
{rows}
 <tr><th colspan="5"><hr></th></tr>
</table></body></html>
""".format(title=html.escape(title), rows="\n".join(body))


RENDERERS = {"links": render_links, "pre": render_pre, "table": render_table}


PLACEHOLDER = """<!DOCTYPE html>
<html lang="pt-BR"><head><meta charset="utf-8"><title>{title}</title></head>
<body><h1>{title}</h1>
<p><strong>Offline snapshot placeholder.</strong> The listing of this folder was
not captured — it exists so that a crawler resolving links on its parent page
still sees a directory (the parent page links to it) instead of a dead link.
It deliberately contains no links, so an inventory stays truthful: nothing is
reported for a folder whose contents were never recorded.</p>
</body></html>
"""


def write_placeholder(out_root: str, site: str, path: str, name: str) -> None:
    target = os.path.join(out_root, site, *[p for p in path.strip("/").split("/") if p],
                          name, "index.html")
    if os.path.exists(target):
        return
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(PLACEHOLDER.format(title=name))


def build(out_root: str, date: str = "2026-09-28") -> List[str]:
    written = []
    for spec in CAPTURES:
        capture = os.path.join(FIXTURES, spec["file"])
        if not os.path.exists(capture):
            continue
        rows = parse_tsv(capture)
        page_url = "https://{}{}".format(spec["site"], spec["path"])
        text = BANNER.format(url=page_url, date=date, capture=spec["file"]) + \
            RENDERERS[spec["dialect"]](rows, spec["site"], spec["path"], spec["title"])
        target_dir = os.path.join(out_root, spec["site"],
                                  *[p for p in spec["path"].strip("/").split("/") if p])
        os.makedirs(target_dir, exist_ok=True)
        target = os.path.join(target_dir, "index.html")
        with open(target, "w", encoding="utf-8") as fh:
            fh.write(text)
        # folders listed here but not captured get a placeholder so that a
        # crawler still resolves them as directories (see PLACEHOLDER)
        for row in rows:
            if row["kind"] == "dir":
                write_placeholder(out_root, spec["site"], spec["path"], row["name"])
        written.append(os.path.relpath(target, out_root))
    return written


def sites_for_config() -> List[Dict[str, object]]:
    """The six sites, with one entry URL per captured listing page."""
    by_slug: Dict[str, Dict[str, object]] = {}
    for spec in CAPTURES:
        url = "https://{}{}".format(spec["site"], spec["path"])
        if spec["site"] not in by_slug:
            by_slug[spec["site"]] = {"slug": spec["site"], "url": url, "urls": []}
        by_slug[spec["site"]]["urls"].append(url)
    out = []
    for slug, site in by_slug.items():
        site["urls"] = [u for u in site["urls"] if u != site["url"]]
        out.append(site)
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="render the real listing snapshots")
    ap.add_argument("--out", default="/tmp/indexclone-snapshots")
    ap.add_argument("--date", default="2026-09-28")
    args = ap.parse_args(argv)
    written = build(args.out, args.date)
    for rel in written:
        print("wrote", os.path.join(args.out, rel))
    return 0


if __name__ == "__main__":
    sys.exit(main())
